CREATE DATABASE CODESOLUTIONS DEFAULT CHARACTER SET utf8;


USE CODESOLUTIONS;


SELECT DATABASE();


CREATE TABLE CLIENTE (
    ID INT,
    NOMBRES VARCHAR(50),
    APELLIDOS VARCHAR(50),
    DIRECCION VARCHAR(50),
    CELULAR CHAR(8),
    DNI CHAR(7),
    SEXO CHAR(1),
    CONSTRAINT CLIENTE_PK PRIMARY KEY (ID)
);


SELECT * FROM CLIENTE;


